#define APPLICATION_ICON				100

#define FOLDERCLOSED_ICON				101
#define FOLDEROPENED_ICON				102

#define TREE_TO_NODE_ICON_OFFSET		100

#define TREE_BOOLEAN_ICON				201
#define TREE_INTEGER_ICON				202
#define TREE_DOUBLE_ICON				203
#define TREE_INTEGERINCREMENTED_ICON	204
#define TREE_DOUBLEINCREMENTED_ICON		205
#define TREE_DOUBLEDISTRIBUTED_ICON		206
#define TREE_ADDITION_ICON				207
#define TREE_SUBTRACTION_ICON			208
#define TREE_MULTIPLICATION_ICON		209
#define TREE_DIVISION_ICON				210
#define TREE_LISTBUILDER_ICON			211
#define TREE_VIEWER_ICON				212
#define TREE_FLOOR_ICON					213
#define TREE_CEIL_ICON					214
#define TREE_ABS_ICON					215
#define TREE_NEGATIVE_ICON				216
#define TREE_SQRT_ICON					217

#define BOOLEAN_ICON					301
#define INTEGER_ICON					302
#define DOUBLE_ICON						303
#define INTEGERINCREMENTED_ICON			304
#define DOUBLEINCREMENTED_ICON			305
#define DOUBLEDISTRIBUTED_ICON			306
#define ADDITION_ICON					307
#define SUBTRACTION_ICON				308
#define MULTIPLICATION_ICON				309
#define DIVISION_ICON					310
#define LISTBUILDER_ICON				311
#define VIEWER_ICON						312
#define FLOOR_ICON						313
#define CEIL_ICON						314
#define ABS_ICON						315
#define NEGATIVE_ICON					316
#define SQRT_ICON						317
